name: Build and Publish
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Test
        run: |
          # Add commands to build and test your package

      - name: Publish Package
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          gx publish --version 1.0.0 --visibility public
        env:
          PACKAGE_NAME: gx-awesome-package
          
